accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name='accounts'
urlpatterns = [
    path('signup/client/', client_signup, name='c_s'),
    path('signup/server/', server_signup, name='s_s'),

    path('client/<int:client_id>/', ClientProfile, name='client_profile'),
    path('server/<int:server_id>/', ServerProfile, name='server_profile'),

    path('client/update/<int:pk>/', ClientUpdate.as_view(), name='client_update'),
    path('server/update/<int:pk>/', ServerUpdate.as_view(), name='server_update'),

    path('category/<int:pk>/', CategoryDetail.as_view(), name='c_detail'),

    path('server/all/', AllServers.as_view(), name='all_server'),

    path('server/<int:pk>/add/experience/', AddExperience.as_view(), name='add_exp'),

    path('server/<int:server_id>/add/ratings/', add_rating, name='add_rate'),

    path('server/<int:server_id>/add/contact/', add_request, name='add_request'),
]

service_app/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.views import home, all_category

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/login/', home, name='home'),
    # path('login/', _login, name='login'),
    path('', home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Online Quiz System'
admin.site.site_title = 'Admin Login'

templates/add_experience.html
{% extends 'base.html' %}
{% block title %}
    Update
{% endblock %}
{% block content %}
    <br><br><br>
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7">
                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <section>
                        {% for field in form %}
                            <div class="form-group">
                                <label class="control-label col-sm-2"><b>{{ field.label_tag }}</b></label>
                                {{ field }}
                            </div>
                        {% endfor %}
                    </section>
                    <button class="btn btn-outline-success btn-lg" type="submit" style="margin-left: 10%;"> Add</button>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/all_server.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    All Server
{% endblock %}
{% block content %}<br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" style="background-color: lightcyan">
                {% if user.is_authenticated %}
                    <table class="table table-bordered" border="0" style="text-align:center;">
                        <thead>
                        <tr>
                            <th>Photo</th>
                            <th>Name</th>
                            <th>Category</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for s in server %}
                            <tr>
                                <td>
                                    <a href="{% url 'accounts:server_profile' s.id %}">
                                    {% if s.image %}
                                        <img class="rounded" src="{{ s.image.url }}" width="70px" height="70px">
                                    {% else %}
                                        <img class="rounded" src="{% static 'service_app/img/blank_profile.png' %}" width="70px"
                                             height="70px">
                                    {% endif %}
                                    </a>
                                </td>
                                <td><a href="{% url 'accounts:server_profile' s.id %}"><b>{{ s.name }}</b></a></td>
                                <td><a href="{% url 'accounts:c_detail' s.category.id %}"><b>{{ s.category }}</b></a> </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>{% block title %}Service App{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'service_app/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'service_app/css/mystyle.css' %}" rel="stylesheet">

</head>
<body style="font-family:lora;" background="{% static 'service_app/img/bg.png' %}">
{% block nav %}
    {% if user.is_authenticated %}

        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd">

            <div class="container">
                <div class="navbar-header">
                    <a href="{% url 'home' %}"><img src="{% static 'service_app/img/logo.png' %}" alt="logo" style="width:40px;"></a>
                    <a class="navbar-brand" href="{% url 'home' %}"><b>Server App</b></a>
                </div>
                <ul class="navbar-nav mr-auto">
                    <li>
                        <a class="nav-link" href="{% url 'home' %}" style="color:#000;"><b>Categories</b></a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'accounts:all_server' %}" style="color:#000;"><b>All
                            Servers</b></a>
                    </li>
                    <li>
                        <a class="nav-link" href="#" style="color:#000;"><b>Contact</b></a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}

                        {% if user.is_client %}
                            <li><a href="{% url 'accounts:client_profile' user.id %}">
                                {% if user.image %}
                                    <img class="rounded-circle" src="{{ user.image.url }}" width="35" height="35"
                                         alt="img">
                                {% else %}
                                    <img class="rounded-circle"
                                         src="{% static 'service_app/img/blank_profile.png' %}" width="35"
                                         height="35">
                                {% endif %}
                                <b>Profile&nbsp;</b></a></li>
                        {% elif user.is_server %}
                            <li><a href="{% url 'accounts:server_profile' user.id %}">
                                {% if user.image %}
                                    <img class="rounded-circle" src="{{ user.image.url }}" width="35" height="35"
                                         alt="img">
                                {% else %}
                                    <img class="rounded-circle"
                                         src="{% static 'service_app/img/blank_profile.png' %}" width="35"
                                         height="35">
                                {% endif %}<b>Profile&nbsp;</b></a></li>
                        {% endif %}
                        <li><a href="{% url 'logout' %}"><b>&nbsp;&nbsp;&nbsp;Logout</b></a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    {% else %}
        <center><br><br>
        <h2><a href="http://127.0.0.1:8000">Login</a></h2>Or
        <h2>SignUp As a <a href="{% url 'accounts:c_s' %}">Client</a> Or <a
                href="{% url 'accounts:s_s' %}">Server</a>
        </h2></center>
    {% endif %}
{% endblock %}
{% block content %}

{% endblock %}


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'service_app/js/jquery-3.3.1.min.js' %}"><\/script>')</script>
<script src="{% static 'service_app/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/category_detail.html
{% extends 'base.html' %}
{% block title %}
    Category
{% endblock %}
{% block content %}<br><br><br>
    {% if user.is_authenticated %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ c.img.url }}" width="300" height="300">
                <h1 style="color:white;"><u>{{ c.category_name }}</u></h1><br>
            </div>
            <div class="col-md-8" style="background-color: lightcyan">


                <ol>
                {% for s in c.server_set.all %}
                   <h3><li><a href="{% url 'accounts:server_profile' s.id %}">{{ s.name }}</a></li></h3>
                {% endfor %}
                </ol>
                {% if c.server_set.count is 0 %}
                    <h1>No Server in this category</h1>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/client_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Profile
{% endblock %}
{% block content %}<br><br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                {% if user.is_authenticated %}
                    {% if c.image %}
                        <img src="{{ c.image.url }}" width="300px" height="300px"><br>
                    {% else %}
                        <img src="{% static 'service_app/img/blank_profile.png' %}" width="300px" height="300px"><br>
                    {% endif %}
                    {% if user.is_client %}
                        {% if user.id == c.id %}
                            <br>
                            <a href="{% url 'accounts:client_update' c.id %}"><h2>Update Your Profile</h2></a><br>
                            {% if servers %}
                                <button type="button" class="btn btn-primary" data-toggle="modal"
                                        data-target="#allRequested">
                                    See all requested server
                                </button>
                            {% else %}
                                <h3>No Request sent</h3>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-8" style="background-color: lightcyan">
                {% if user.is_authenticated %}
                    <h3>Name: {{ c.name }}</h3><br>
                    <h3>Address: {{ c.address }}</h3><br>
                    {% if c.gender == 'M' %}
                        <h3>Gender: Male</h3><br>
                    {% else %}
                        <h3>Gender: Female</h3><br>
                    {% endif %}
                    <h3>Phone: {{ c.phone }}</h3><br>
                    <h3>Birth Date: {{ c.birth_date }}</h3><br>
                    <h3>Joined Date: {{ c.joined_date }}</h3><br>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- All requested Client Modal -->
    <div class="modal fade" id="allRequested">
        <div class="modal-dialog modal-dialog-centered  modal-lg">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Modal Heading</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Image</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Category</th>
                            <th>Details</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            {% for s in servers %}
                                <td>{{ forloop.counter }}</td>
                                <td>
                                    {% if s.image %}
                                        <img class="rounded" src="{{ s.image.url }}" width="70px"
                                             height="70px">
                                    {% else %}
                                        <img class="rounded"
                                             src="{% static 'service_app/img/blank_profile.png' %}"
                                             width="70px"
                                             height="70px">
                                    {% endif %}
                                </td>
                                <td>{{ s.name }}</td>
                                <td>{{ s.phone }}</td>
                                <td>{{ s.category }}</td>
                                <td><a href="{% url 'accounts:server_profile' s.id %}">View Details</a>
                                </td></tr>
                            {% endfor %}

                        </tr>
                        </tbody>
                    </table>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Home
{% endblock %}
{% block content %}<br><br><br>
    {% if user.is_authenticated %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 11 %}"><img src="{% static 'service_app/img/Icon/advocate.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Advocate</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 12 %}"><img src="{% static 'service_app/img/Icon/architecture.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Architecture</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 6 %}"><img src="{% static 'service_app/img/Icon/rent  car.png' %}" width="100" height="100"></a>
                <h4 style="color:white;">Rent Car</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 5 %}"><img src="{% static 'service_app/img/Icon/shifting.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Shifting</h4>
            </div>
        </div><hr>
        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 4 %}"><img src="{% static 'service_app/img/Icon/carpenter.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Carpenter</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 3 %}"><img src="{% static 'service_app/img/Icon/mason.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Mason</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 1 %}"><img src="{% static 'service_app/img/Icon/electrician.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Electrician</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 8 %}"><img src="{% static 'service_app/img/Icon/decorator.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Decorator</h4>
            </div>
        </div><hr>
        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 9 %}"><img src="{% static 'service_app/img/Icon/home tutor.png' %}" width="100" height="100"></a>
                <h4 style="color:white;">Home Tutor</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 7 %}"><img src="{% static 'service_app/img/Icon/cook.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Cook</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 2 %}"><img src="{% static 'service_app/img/Icon/plumber 2.jpg' %}" width="100" height="100"></a>
                <h4 style="color:white;">Plumber</h4>
            </div>
            <div class="col-md-3">
                <a href="{% url 'accounts:c_detail' 13 %}"><img src="{% static 'service_app/img/Icon/others.png' %}" width="100" height="100"></a>
                <h4 style="color:white;">Others</h4>
            </div>
        </div>
    </div><hr>
    {% endif %}
{% endblock %}

templates/server_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Profile
{% endblock %}
{% block content %}<br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {% if user.is_authenticated %}
                    {% if s.image %}
                        <img src="{{ s.image.url }}" width="300px" height="300px"><br>
                    {% else %}
                        <img src="{% static 'service_app/img/blank_profile.png' %}" width="300px" height="300px"><br>
                    {% endif %}
                    {% if user.is_server %}
                        {% if user.id == s.id %}
                            <br>
                            <a href="{% url 'accounts:server_update' s.id %}"><h2>Edit Profile</h2></a><br>
                            <h2><a href="{% url 'accounts:add_exp' s.id %}">Add Experience</a></h2><br>
                            {% if cl %}
                                <button type="button" class="btn btn-primary" data-toggle="modal"
                                        data-target="#allRequested">
                                    See all request
                                </button>
                            {% else %}
                                <h3>No Request</h3>
                            {% endif %}

                        {% endif %}
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-8" style="background-color: lightcyan">
                {% if user.is_authenticated %}
                    <h3>Name: {{ s.name }}</h3><br>
                    {% if s.gender == 'M' %}
                        <h3>Gender: Male</h3><br>
                    {% else %}
                        <h3>Gender: Female</h3><br>
                    {% endif %}
                    <h3>Address: {{ s.address }}</h3><br>
                    <h3>Birth Date: {{ s.birth_date }}</h3><br>
                    <h3>Joined Date: {{ s.joined_date }}</h3><br>
                    <h3>Experience: {{ s.experience }}</h3><br>


                    <h3 style="color: #6610f2">Rating: </h3>
                    {% for i in f_s %}
                        <img src="{% static 'service_app/img/Star (Full).png' %}" width="30px" height="30px">
                    {% endfor %}
                    {% for i in h_s %}
                        <img src="{% static 'service_app/img/Star (Half Full).png' %}" width="30px" height="30px">
                    {% endfor %}
                    {% for i in n_s %}
                        <img src="{% static 'service_app/img/Star (Empty).png' %}" width="30px" height="30px">
                    {% endfor %}
                    <p>{{ s.avg_rate }}/5,&nbsp;{{ s.number_of_rating }}
                        {% if s.number_of_rating > 1 %}
                            votes
                        {% else %}
                            vote
                        {% endif %}
                    </p>

                    {% if user.is_client %}
                        {% if is_requested %}
                            <h3>Request Sent</h3>
                        {% else %}
                            <form method="post" action="{% url 'accounts:add_request' s.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="client" value="{{ user.id }}">
                                <input id="req_id" type="submit" class="btn btn-primary"
                                       value="Send Request">
                            </form>
                        {% endif %}
                    {% endif %}
                    <br>
                    {% if  user.name != s.name %}
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                            {% if s.gender == 'M' %}
                                Rate Him
                            {% else %}
                                Rate Her
                            {% endif %}
                        </button>
                    {% endif %}

                    <button type="button" class="btn btn-primary" onclick="myFunction()">Contact</button>
                    <div id="phone" style="display: none">
                        <h3>Phone: {{ s.phone }}</h3>
                    </div>
                    <!-- Rating Modal -->
                    <div class="modal fade" id="myModal">
                        <div class="modal-dialog  modal-dialog-centered  modal-sm">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Rate</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <center>
                                        <form method="post" action="{% url 'accounts:add_rate' s.id %}">
                                            {% csrf_token %}
                                            <input type="number" min="0" max="5" name="ratings" value="4"><br><br>
                                            <input type="submit" class="btn btn-primary" value="Rate">
                                        </form>
                                    </center>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- All requested Client Modal -->
                    <div class="modal fade" id="allRequested">
                        <div class="modal-dialog modal-dialog-centered  modal-lg">
                            <div class="modal-content">

                                <!-- Modal Header -->
                                <div class="modal-header">
                                    <h4 class="modal-title">Modal Heading</h4>
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                                <!-- Modal body -->
                                <div class="modal-body">
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Profile</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            {% for c in cl %}
                                                <td>{{ forloop.counter }}</td>
                                                <td>
                                                    {% if c.image %}
                                                        <img class="rounded" src="{{ c.image.url }}" width="70px"
                                                             height="70px">
                                                    {% else %}
                                                        <img class="rounded"
                                                             src="{% static 'service_app/img/blank_profile.png' %}"
                                                             width="70px"
                                                             height="70px">
                                                    {% endif %}
                                                </td>
                                                <td>{{ c.name }}</td>
                                                <td>{{ c.phone }}</td>
                                                <td><a href="{% url 'accounts:client_profile' c.id %}">View Profile</a>
                                                </td></tr>
                                            {% endfor %}

                                        </tr>
                                        </tbody>
                                    </table>
                                </div>

                                <!-- Modal footer -->
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                </div>

                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <script>
        function myFunction() {
            var x = document.getElementById("phone");
            if (x.style.display === "none") {
                x.style.display = "block";
            } else {
                x.style.display = "none";
            }
        }
    </script>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}
    SignUp
{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7" style="background-color: lightcyan">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <section>
                        {% for field in form %}
                            <div class="form-group">
                                <label class="control-label col-sm-2"><b>{{ field.label_tag }}</b></label>
                                {{ field }}
                            </div>
                        {% endfor %}
                    </section>
                    <button class="btn btn-success btn-lg" type="submit" style="margin-left: 20%;">SignUp
                    </button>
                    <button class="btn btn-warning btn-lg"><a href="{% url 'home' %}">Cancel</a>
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block title %}
    Update
{% endblock %}
{% block content %}
    <br><br><br>
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3"></div>
            <div class="col-sm-7" style="background-color: lightcyan">
                <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <section>
                        {% for field in form %}
                            <div class="form-group">
                                <label class="control-label col-sm-2"><b>{{ field.label_tag }}</b></label>
                                {{ field }}
                            </div>
                        {% endfor %}
                    </section>
                    <button class="btn btn-outline-success btn-lg" type="submit" style="margin-left: 10%;">Update
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}